#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80 make it return a page with
# "Hello World" in it

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
service nginx start
