#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80 make it return a page with
# "Hello World" in it
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo service nginx start
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
