#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
# ensuring nginx is running and listening on port 80 of all the server’s active IPv4 IPs


ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
